### ISSUE TITLE
Support python 3.8 and 3.9

### ISSUE THREAD

**Issue by rainman110** [DLR-SC/tixi#178] opened 2021-03-05 08:21 UTC
We should also check issue #177 , which indicates an issue for DLL loading on windows with python 3.8.

**Comment by joergbrech** [comment] 2021-03-05 08:26
This is related to/a duplicate of #165 and https://github.com/DLR-SC/tigl-conda/issues/13.

**Comment by ArneBachmannDLR** [comment] 2021-04-01 06:19
Regarding #165 I was able to import `tixi3.tixi3wrapper` by switching back to a Miniforge 3.7 environment. My PATH is about 1394 characters long which is [supposed to be still OK](https://software.intel.com/content/www/us/en/develop/articles/limitation-to-the-length-of-the-system-path-variable.html)

**Closed** 2021-11-16 15:17 UTC

**Comment by ArneBachmannDLR** [comment] 2023-10-24 12:51
We just had to apply this workaround for a colleague that re-installed mambaforge 10 with a 3.9 environment... Works fine on the console, but no dice from within PyCharm, even after re-adding system interpreter and the conda environment. Just weird

**Comment by joergbrech** [comment] 2023-10-24 14:26
Interesting, I encountered the same problem when migrating to mambaforge. PyCharm seems to be the troublemaker here: It seems liek it uses a slightly different environment then the plain conda env. Please let me know if re-installation solved your issue.

**Comment by ArneBachmannDLR** [comment] 2023-10-24 15:05
No, didn't help. We checked PATH and sys.path, it seems the Library/bin folder was missing at runtime. The workaround with the absolute DLL path worked, however. I'll check back with the user

**Comment by joergbrech** [comment] 2023-11-08 15:54
We solved this issue by downgrading PyCharm to 2022.2.2 for now. I still haven't figured out what the underlying problem is.
